[workspace]
resolver = "2"
members = [
	"inference",
	"training",
	"model"
]

[workspace.package]
edition = "2021"
license = "MIT OR Apache-2.0"
version = "0.1.0"

[workspace.dependencies]
burn = { version = "0.14.0", features = ["wgpu"] }
burn-import = { version = "0.14.0" }
