[workspace]
resolver = "2"
members = ["inference", "training", "model"]

[workspace.package]
edition = "2021"
license = "MIT OR Apache-2.0"
version = "0.1.0"

[workspace.dependencies]
burn = { version = "0.15.0", default-features = false }
burn-import = { version = "0.15.0" }
