[package]
name = "model"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
burn = { workspace = true }
num_enum = { version = "0.7.3", default-features = false }
