[package]
name = "training"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
burn = { workspace = true, features = ["train", "vision", "wgpu" ] }
csv = "1.3.0"
model = { path = "../model" }
rand = "0.8.5"
serde = "1.0.210"
