[package]
name = "training"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
burn = { workspace = true, features = ["train", "vision"] }
model = { path = "../model" }
